version: '3.3'

services:

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    # restart: always
    environment:
      MYSQL_DATABASE: dbnlwvaloriza
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123qwe
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
       
networks:
  back:
  
volumes:
  db:
